---
name: orders_cases_events
version: 1.0.0
config-version: 2

profile: bolt-databricks

model-paths: [models]
macro-paths: [macros]
seed-paths: [seeds]

target-path: target
clean-targets:
  - target
  - dbt_packages

vars:
  # execution_date from Airflow
  data_interval_start: '2022-08-24 12:00:00'
  # next_execution_date from Airflow
  data_interval_end: '2022-08-24 13:00:00'

models:
  orders_cases_events:
    +materialized: view
    +file_format: delta
    staging:
      +docs:
        node_color: silver
    intermediate:
      +docs:
        node_color: gray
    core:
      +docs:
        node_color: LightSeaGreen
    marts:
      +docs:
        node_color: darkred
